version: '3'

volumes:
  logs:
  static:
  media:

services:
  cache:
    image: redis:latest
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${GEOCURRENCY_DB_NAME}
      - POSTGRES_USER=${GEOCURRENCY_DB_USERNAME}
      - POSTGRES_PASSWORD=${GEOCURRENCY_DB_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
  geocurrency:
    image: fmeurou/geocurrency:latest
    command: "/usr/bin/supervisord -c /etc/supervisor/conf.d/api.conf"
    environment:
      - GEOCURRENCY_DB_ENGINE=${GEOCURRENCY_DB_ENGINE}
      - GEOCURRENCY_DB_HOST=${GEOCURRENCY_DB_HOST}
      - GEOCURRENCY_DB_PORT=${GEOCURRENCY_DB_PORT}
      - GEOCURRENCY_DB_NAME=${GEOCURRENCY_DB_NAME}
      - GEOCURRENCY_DB_USERNAME=${GEOCURRENCY_DB_USERNAME}
      - GEOCURRENCY_DB_PASSWORD=${GEOCURRENCY_DB_PASSWORD}
      - GEOCURRENCY_SECRET_KEY=${GEOCURRENCY_SECRET_KEY}
      - GEOCURRENCY_URL=${GEOCURRENCY_HOST}
      - GEOCURRENCY_ENV=Docker
      - GEOCURRENCY_CONTACT_EMAIL=${GEOCURRENCY_CONTACT_EMAIL}
    volumes:
      - logs:/var/log
      - static:/var/apps/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
  migration:
    image: fmeurou/geocurrency:latest
    command: python /var/apps/api/manage.py migrate --noinput
    environment:
      - GEOCURRENCY_DB_ENGINE=${GEOCURRENCY_DB_ENGINE}
      - GEOCURRENCY_DB_HOST=${GEOCURRENCY_DB_HOST}
      - GEOCURRENCY_DB_PORT=${GEOCURRENCY_DB_PORT}
      - GEOCURRENCY_DB_NAME=${GEOCURRENCY_DB_NAME}
      - GEOCURRENCY_DB_USERNAME=${GEOCURRENCY_DB_USERNAME}
      - GEOCURRENCY_DB_PASSWORD=${GEOCURRENCY_DB_PASSWORD}
      - GEOCURRENCY_SERVICE_EMAIL=${GEOCURRENCY_ADMIN_EMAIL}
      - GEOCURRENCY_SERVICE_URL=${GEOCURRENCY_HOST}
    depends_on:
      - geocurrency
  superuser:
    image: fmeurou/geocurrency:latest
    command: python /var/apps/api/manage.py shell -c "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'T3st2020.')"
    environment:
      - GEOCURRENCY_DB_ENGINE=${GEOCURRENCY_DB_ENGINE}
      - GEOCURRENCY_DB_HOST=${GEOCURRENCY_DB_HOST}
      - GEOCURRENCY_DB_PORT=${GEOCURRENCY_DB_PORT}
      - GEOCURRENCY_DB_NAME=${GEOCURRENCY_DB_NAME}
      - GEOCURRENCY_DB_USERNAME=${GEOCURRENCY_DB_USERNAME}
      - GEOCURRENCY_DB_PASSWORD=${GEOCURRENCY_DB_PASSWORD}
    depends_on:
      - migration
  fetch_rates:
    image: fmeurou/geocurrency:latest
    command: python /var/apps/api/manage.py fetch_rates
    environment:
      - GEOCURRENCY_DB_ENGINE=${GEOCURRENCY_DB_ENGINE}
      - GEOCURRENCY_DB_HOST=${GEOCURRENCY_DB_HOST}
      - GEOCURRENCY_DB_PORT=${GEOCURRENCY_DB_PORT}
      - GEOCURRENCY_DB_NAME=${GEOCURRENCY_DB_NAME}
      - GEOCURRENCY_DB_USERNAME=${GEOCURRENCY_DB_USERNAME}
      - GEOCURRENCY_DB_PASSWORD=${GEOCURRENCY_DB_PASSWORD}
    depends_on:
      - migration
  lb:
    build: lb/
    ports:
      - "80:80"
    volumes:
      - static:/var/www/static
    depends_on:
      - geocurrency
