# Generated by Django 3.0.5 on 2020-04-10 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('numeric', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('exponent', models.IntegerField()),
                ('countries', models.ManyToManyField(related_name='currencies', through='currencies.CurrencyCountry', to='countries.Country')),
            ],
        ),
        migrations.AddField(
            model_name='currencycountry',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.CurrencyModel'),
        ),
        migrations.CreateModel(
            name='ConversionRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.FloatField()),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_conversions', to='currencies.CurrencyModel')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='currencies.CurrencyModel')),
            ],
            options={
                'unique_together': {('currency', 'base_currency', 'date')},
            },
        ),
    ]
